# Generated by Django 5.2 on 2025-06-26 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('registation_number', models.CharField(max_length=20)),
                ('seat_capacity', models.PositiveIntegerField()),
                ('aircraft_image', models.ImageField(blank=True, null=True, upload_to='aircrafts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='flightowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('Companyname', models.CharField(max_length=100)),
                ('bussiness_registration_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50)),
                ('years_of_operation', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('number_of_aircrafts', models.PositiveIntegerField()),
                ('flight_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International'), ('cargo', 'Cargo'), ('charter', 'Charter')], max_length=50)),
                ('airline_code', models.PositiveIntegerField(blank=True, null=True)),
                ('airline_license', models.FileField(upload_to='documents/licenses/')),
                ('registration_certificate', models.FileField(upload_to='documents/certificates/')),
                ('government_id_proof', models.FileField(upload_to='documents/id_proofs/')),
                ('agree_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('registration_number', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('total_rooms', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('business_class_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('economy_class_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter tax as percentage e.g. 18.00 for 18%', max_digits=5)),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'cancelled')], default='scheduled', max_length=20)),
                ('baggage_allowance', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.aircraft')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='owner.flightowner'),
        ),
    ]
