# Generated by Django 5.2 on 2025-06-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightowner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
