# Generated by Django 5.2 on 2025-07-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_flightowner_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'cancelled'), ('landed', 'Landed')], default='scheduled', max_length=20),
        ),
    ]
