# Generated by Django 5.2 on 2025-07-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_hotel_image_booking_guestdetail_hotelsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
