# Generated by Django 5.2 on 2025-07-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_remove_room_is_available_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
