# Generated by Django 5.2 on 2025-06-26 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=20)),
                ('arrival', models.CharField(max_length=20)),
                ('departure_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('passengers', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(unique=True)),
                ('phonenumber', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.PositiveIntegerField()),
                ('selected_seats', models.TextField(blank=True, help_text='comma-seperated  seat codes (e.g. 5A,5B)')),
                ('total_price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Confirmed', 'confirmed'), ('Pending', 'pending'), ('Cancelled', 'cancelled')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='Review_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userregister')),
            ],
        ),
    ]
