# Generated by Django 5.2 on 2025-06-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_passwordresetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
