# Generated by Django 5.2 on 2025-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notification_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_booking',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Cancelled', 'cancelled')], default='Active', max_length=20),
        ),
    ]
