# Generated by Django 5.2 on 2025-07-03 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_review_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='passenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.review_booking'),
            preserve_default=False,
        ),
    ]
